### ISSUE TITLE
Issue running Pydidas on aarch64 (Nvidia Jetson)

### ISSUE THREAD

**Issue by vamatya** [hereon-GEMS/pydidas#64] opened 2024-08-30 20:11 UTC
Hi! 

I was able to install Pydidas throught the following route:
* OS: Ubuntu 20.04
* Arch: aarch64 (Nvidia Jetson)
* Build from source
  *  Disable pyqt dependencies in requirements.txt
  * `conda install pyqt pyqt5-sip pyqtchart pyqtwebengine`
  * `python -m pip install . `
 
With the above, I'm able to install, but pydidas fails to run with following log: 

============================================================
Running Sphinx v7.3.7
making output directory... done
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 115 source files that are out of date
updating environment: [new config] 115 added, 0 changed, 0 removed
reading sources... [100%] manuals/quickstart
/home/vamatya/miniconda3/envs/test1/lib/python3.11/site-packages/pydidas/core/dataset.py:docstring of pydidas.core.dataset.Dataset:17: ERROR: Unexpected indentation.
/home/vamatya/miniconda3/envs/test1/lib/python3.11/site-packages/pydidas/core/dataset.py:docstring of pydidas.core.dataset.Dataset:21: WARNING: Block quote ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] manuals/quickstart
generating indices... genindex py-modindex done
writing additional pages... search done
copying images... [100%] manuals/gui/windows/images/user_config_overview.png
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 3 warnings.

The HTML pages are in ../../miniconda3/envs/test1/lib/python3.11/site-packages/pydidas/sphinx/html.
Traceback (most recent call last):
  File "/home/vamatya/miniconda3/envs/test1/bin/pydidas-gui", line 8, in <module>
    sys.exit(run_gui())
             ^^^^^^^^^
  File "/home/vamatya/miniconda3/envs/test1/lib/python3.11/site-packages/pydidas_scripts/pydidas_gui.py", line 115, in run_gui
    _ = start_pydidas_gui(_splash, restore_state="exit")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vamatya/miniconda3/envs/test1/lib/python3.11/site-packages/pydidas_scripts/pydidas_gui.py", line 54, in start_pydidas_gui
    from pydidas.core import UserConfigError
  File "/home/vamatya/miniconda3/envs/test1/lib/python3.11/site-packages/pydidas/__init__.py", line 121, in <module>
    _param = core.get_generic_parameter(_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vamatya/miniconda3/envs/test1/lib/python3.11/site-packages/pydidas/core/generic_parameters.py", line 76, in get_generic_parameter
    return Parameter(refkey, _type, _default, **_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vamatya/miniconda3/envs/test1/lib/python3.11/site-packages/pydidas/core/parameter.py", line 171, in __init__
    self.__type = _get_base_class(param_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vamatya/miniconda3/envs/test1/lib/python3.11/site-packages/pydidas/core/parameter.py", line 63, in _get_base_class
    if issubclass(cls, Integral):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: issubclass() arg 1 must be a class

============================================================
Is there a suggestion how to make pydidas run on aarch64 - Ubuntu 20.04? 

Thanks!
Vinay

**Comment by malte-storm** [comment] 2024-09-03 13:31
Hi Vinay,

sorry for the delay in the reply. That is an interesting error because it should not occur at all, irrespective of the platform. 

If you are happy to fiddle around a bit, could you replace the ```_get_base_class``` function in the paraemter.py with the following code:

```
def _get_base_class(cls: Any) -> Union[type, Real, Integral, None]:
    """
    Filter numerical classes and return the corresponding abstract base class.

    This function checks whether cls is a numerical class and returns the
    numerical abstract base class from the numbers module for type-checking.
    Any other class will be returned.

    Parameters
    ----------
    cls : object
        The concrete class.

    Returns
    -------
    object
        The base class of the input class if the input.
    """
    if cls is None:
        return None
    try:
        if issubclass(cls, Integral):
            return Integral
        if issubclass(cls, Real):
            return Real
    except TypeError:
        print(f"The input object {cls} is not a class instance but of type {type(cls)}")
    return cls
```

and run it again? If you give me the print output, I can understand the issue better and hopefully fix it.

**Comment by vamatya** [comment] 2024-09-03 17:13
Hi Malte, 

I tried the function in `parameter.py` and re-installed pydidas. It seems to work now. Not sure, why I was getting the error earlier.

**Comment by malte-storm** [comment] 2024-09-04 07:35
And did you get any error outputs from the except statement? Both before and after the reinstall?

**Comment by malte-storm** [comment] 2024-09-11 12:54
Digging into the problem, this issue was caused by the sphinx-build of the documentation. 
It occured only when the sphinx (>7) was called from the same process. Moving the sphinx-build to a subprocess solved the issue.

The fix will be included in the next release.

**Closed by malte-storm** 2024-09-11 12:54 UTC
